[build]
  command = "hugo --minify"
  publish = "public"

[context.production.environment]
  HUGO_VERSION = "0.147.8"

[build.environment]
  HUGO_ENV = "production"

[[redirects]]
  from = "/tiki-index.php"
  to = "/"
  status = 301
  force = true
